package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ControlesAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertControlesAllPropertiesEquals(Controles expected, Controles actual) {
        assertControlesAutoGeneratedPropertiesEquals(expected, actual);
        assertControlesAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertControlesAllUpdatablePropertiesEquals(Controles expected, Controles actual) {
        assertControlesUpdatableFieldsEquals(expected, actual);
        assertControlesUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertControlesAutoGeneratedPropertiesEquals(Controles expected, Controles actual) {
        assertThat(expected)
            .as("Verify Controles auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertControlesUpdatableFieldsEquals(Controles expected, Controles actual) {
        assertThat(expected)
            .as("Verify Controles relevant properties")
            .satisfies(e -> assertThat(e.getNombre()).as("check nombre").isEqualTo(actual.getNombre()))
            .satisfies(e -> assertThat(e.getDescripcion()).as("check descripcion").isEqualTo(actual.getDescripcion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertControlesUpdatableRelationshipsEquals(Controles expected, Controles actual) {
        assertThat(expected)
            .as("Verify Controles relationships")
            .satisfies(e -> assertThat(e.getRiesgos()).as("check riesgos").isEqualTo(actual.getRiesgos()));
    }
}
