package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class VulnerabilidadesAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVulnerabilidadesAllPropertiesEquals(Vulnerabilidades expected, Vulnerabilidades actual) {
        assertVulnerabilidadesAutoGeneratedPropertiesEquals(expected, actual);
        assertVulnerabilidadesAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVulnerabilidadesAllUpdatablePropertiesEquals(Vulnerabilidades expected, Vulnerabilidades actual) {
        assertVulnerabilidadesUpdatableFieldsEquals(expected, actual);
        assertVulnerabilidadesUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVulnerabilidadesAutoGeneratedPropertiesEquals(Vulnerabilidades expected, Vulnerabilidades actual) {
        assertThat(expected)
            .as("Verify Vulnerabilidades auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVulnerabilidadesUpdatableFieldsEquals(Vulnerabilidades expected, Vulnerabilidades actual) {
        assertThat(expected)
            .as("Verify Vulnerabilidades relevant properties")
            .satisfies(e -> assertThat(e.getNombre()).as("check nombre").isEqualTo(actual.getNombre()))
            .satisfies(e -> assertThat(e.getDescripcion()).as("check descripcion").isEqualTo(actual.getDescripcion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVulnerabilidadesUpdatableRelationshipsEquals(Vulnerabilidades expected, Vulnerabilidades actual) {
        // empty method
    }
}
