import dayjs from 'dayjs/esm';
import { IGrupoActivos } from 'app/entities/grupo-activos/grupo-activos.model';
import { IControles } from 'app/entities/controles/controles.model';
import { IAmenazas } from 'app/entities/amenazas/amenazas.model';
import { IVulnerabilidades } from 'app/entities/vulnerabilidades/vulnerabilidades.model';
import { TipoRiesgo } from 'app/entities/enumerations/tipo-riesgo.model';
import { Clasificacion } from 'app/entities/enumerations/clasificacion.model';
import { AfectacionEconomica } from 'app/entities/enumerations/afectacion-economica.model';
import { AfectacionReputacional } from 'app/entities/enumerations/afectacion-reputacional.model';
import { ProbabilidadInherente } from 'app/entities/enumerations/probabilidad-inherente.model';
import { ImpactoInherente } from 'app/entities/enumerations/impacto-inherente.model';
import { ZonaRiesgo } from 'app/entities/enumerations/zona-riesgo.model';
import { Afectacion } from 'app/entities/enumerations/afectacion.model';
import { TipoControl } from 'app/entities/enumerations/tipo-control.model';
import { Implementacion } from 'app/entities/enumerations/implementacion.model';
import { FrecuenciaControl } from 'app/entities/enumerations/frecuencia-control.model';
import { ProbabilidadResidualFinal } from 'app/entities/enumerations/probabilidad-residual-final.model';
import { ImpactoResidualFinal } from 'app/entities/enumerations/impacto-residual-final.model';
import { ZonaRiesgoFinalControl } from 'app/entities/enumerations/zona-riesgo-final-control.model';
import { TratamientoRiesgo } from 'app/entities/enumerations/tratamiento-riesgo.model';

export interface IRiesgo {
  id: number;
  proceso?: string | null;
  tipoRiesgo?: keyof typeof TipoRiesgo | null;
  descripcion?: string | null;
  clasificacion?: keyof typeof Clasificacion | null;
  frecuencia?: number | null;
  afectacionEconomica?: keyof typeof AfectacionEconomica | null;
  impactoReputacional?: keyof typeof AfectacionReputacional | null;
  probabilidadInherente?: keyof typeof ProbabilidadInherente | null;
  impactoInherente?: keyof typeof ImpactoInherente | null;
  zonaRiesgo?: keyof typeof ZonaRiesgo | null;
  afectacion?: keyof typeof Afectacion | null;
  tipoControl?: keyof typeof TipoControl | null;
  implementacion?: keyof typeof Implementacion | null;
  calificacionControl?: number | null;
  documentado?: boolean | null;
  frecuenciaControl?: keyof typeof FrecuenciaControl | null;
  evidencia?: boolean | null;
  probabilidad?: number | null;
  impacto?: number | null;
  probabilidadResidualFinal?: keyof typeof ProbabilidadResidualFinal | null;
  impactoResidualFinal?: keyof typeof ImpactoResidualFinal | null;
  zonaDeRiesgoFinal?: keyof typeof ZonaRiesgoFinalControl | null;
  riesgoResidual?: string | null;
  tratamiento?: keyof typeof TratamientoRiesgo | null;
  planAccion?: string | null;
  responsable?: string | null;
  fechaImplementacion?: dayjs.Dayjs | null;
  seguimientoControlExistente?: string | null;
  estado?: string | null;
  observaciones?: string | null;
  fechaMonitoreo?: dayjs.Dayjs | null;
  activos?: Pick<IGrupoActivos, 'id' | 'nombre'>[] | null;
  controles?: Pick<IControles, 'id' | 'nombre'>[] | null;
  amenaza?: Pick<IAmenazas, 'id' | 'nombre'> | null;
  vulnerabilidad?: Pick<IVulnerabilidades, 'id' | 'nombre'> | null;
}

export type NewRiesgo = Omit<IRiesgo, 'id'> & { id: null };
